#!/bin/bash

# Variables
break=0
confirmation=0

# Formatting
startUnderline=$(tput smul)
endUnderline=$(tput rmul)
RED="\e[31m"
ENDCOLOR="\e[0m"
bold=$(tput bold)
normal=$(tput sgr0)

clear
echo "${bold}Booking Management Menu${normal}"

echo -e "\n 1 -- Book Venue"
echo " 2 -- Venue Booking Report"
echo -e "\n Q -- Back to Previous Page\n"

while [ "$break" -lt 1 ]; do
    read -p "Please select a choice: " choice
    
    case "$choice" in
        1) bash staffDetailValidate;;
        2) bash staffDetailValidate;;
        [Qq])
            break=1
            echo "Back to ${bold}University Venue${normal} Management Menue" 
            sleep 1
            bash mainMenu;;
        *) echo -e "\n${RED}Invalid choice input. Do try again.${ENDCOLOR}\n";;
    esac
done
