#!/bin/bash

#Variables
booking=./booking.txt

# Let system only read room number format [SG0001]
function isrNumValid() {
regex="^(K|B|SG)[0-9]{1,3}[a-zA-Z]{0,1}$"
local rNum="$1"

if [[ "$rNum" =~ $regex ]]; then
    echo $TRUE
else
    echo $FALSE
fi

}

#Let system only read date format [mm/dd/yyyy]
function isDateValid() {
regex="^(0[1-9]|1[012])\/(0[1-9]|[12][0-9]|3[01])\/(19|20)[0-9]{2}$"
local date="$1"

if [[ "$date" =~ $regex ]]
then
echo $TRUE
else
echo $FALSE
fi
}

#Let system only read 24-hour clock time
function isTimeValid() {
local time="$1"
regex="^([01][0-9]|2[0-3]):[0-5][0-9]$"

if [[ "$time" =~ $regex ]]
then
echo $TRUE
else
echo $FALSE
fi
}

#Time To must at least 1 hour after Time From
function validateTimeToFrom() {
local timeFrom="$1"
local timeTo="$2"
local timestampFrom=$(date -d "$timeFrom" +%s)
local timestampTo=$(date -d "$timeTo" +%s)
local time_diff=$(( timestampTo - timestampFrom ))

if [[ "$time_diff" -ge 3540 ]] 
then
echo $TRUE
else
echo $FALSE
fi
}

#Check for overlapping bookings
function isBookingValid() {
  local roomNum="$1"
  local bookingDate="$2"
  local timeFrom="$3"
  local timeTo="$4"
}
