#!/bin/bash

#Let system read room number format [BlockName+Number]
function isRoomNumValid() {
local roomNum="$1"
regex="^[[:digit:]]{1,3}[a-zA-Z]{0,1}$"

if [[ "$roomNum" =~ $regex ]]; then
    echo $TRUE
else
    echo $FALSE
fi
}

#Let system read only number
function isCapacityValid() {
regex="^[[:digit:]]{2,3}$"
local capacity="$1"

if [[ "$capacity" =~ $regex ]]; then
    echo $TRUE
else
    echo $FALSE
fi
}

function isRemarksValid() {
regex="^.{1,30}$"
local remarks="$1"

if [[ "$remarks" =~ $regex ]]; then
    echo $TRUE
else
    echo $FALSE
fi
}
